repos:
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.12.2
    hooks:
      - id: markdown-link-check
        args: ["--quiet"]
  - repo: local
    hooks:
      - id: pytest-fast
        name: pytest-fast
        entry: .venv/bin/pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["-m", "fast", "-v"]
